### PR TITLE
Update auth.ts

### PR DESCRIPTION
**Pull request by LutherTS**
redirectURI: redirectUri
That was the final reason why the demo was not working.

### CODE REVIEW

**Comment by andy-hook** [comment]
Hey @LutherTS, this casing should already be correct per the `@workos-inc/node: 4.0.0` version listed in the package file.

Are you using a different version of the SDK in your local project?

**Comment by LutherTS** [comment]
Hi Andy, on my package.json it says `"@workos-inc/node": "^4.0.1"`. Without attributing `redirectUri` to `redirectURI` I was only getting a general error.

**Comment by andy-hook** [comment]
Thanks @LutherTS, I've also spotted this issue with the patch `4.0.1`, can you try the latest `5.1.1` release in your project and let me know if this resolves this issue? I'll raise a change to update the dependencies here.

**Comment by LutherTS** [comment]
@andy-hook You're correct, the initial case with just `redirectUri` works on the `5.1.1` release `@latest`. I don't know why the `npm install @workos-inc/node` proposed in the WorkOS dashboard made me install `4.0.1` instead.

**Comment by LutherTS** [comment]
That being said, now the issue I'm having is once I sign up and login, I'm being sent to the callback page with a code in the searchParams but nothing happens. No redirect to the Account page, just this attached blank page. 

Capture d’écran 2024-01-17 à 12 59 01

**Comment by andy-hook** [comment]
Do you receive any additional information after updating your `route.ts` file like this?

https://github.com/workos/next-authkit-example/blob/adjust-error-handling/src/app/callback/route.ts#L46-L48

**Comment by LutherTS** [comment]
Here it is: `error	"JWT_SECRET_KEY is not set"`
And indeed, I don't have any JWT_SECRET_KEY in .env.local, I didn't find it suggested in the README file. Can you tell me how I can set that up?

**Comment by andy-hook** [comment]
You can create one by following [these steps]( https://workos.com/docs/user-management/3-handle-the-user-session/create-a-signing-secret).

Let me know if you run into any other issues.

**Comment by LutherTS** [comment]
Thanks. Now it works and I get signed in. 
But if I try to go to the account page I'm getting asked to sign in again making it effectively impossible to reach the account page. Is it something that has to do with middleware? 

Capture d’écran 2024-01-17 à 13 29 37

**Comment by LutherTS** [comment]
@andy-hook It works now. I can reach and see the account page. 

Capture d’écran 2024-01-17 à 13 43 21

**Comment by andy-hook** [comment]
@LutherTS Great, we'll update the readme to make this easier for folks in the future.

I'm going to close this PR in favour of a dependency update https://github.com/workos/next-authkit-example/pull/9

Thanks for raising!

**Pull request closed without merging**
